### ISSUE TITLE
Minecraft 1.16.4 src

### ISSUE THREAD

**Issue by AyHa1810** [AyHa1810/Anything#3]
@Iscle or @LegacyGamerHD, if you read this, then, can you decompile Minecraft Java 1.16.4 for me?

Here, sharing some resources to decompile it very easily

Enigma Decompiler
 > [Builds](https://maven.fabricmc.net/cuchaz/)
 > [Src Repo](https://github.com/FabricMC/Enigma)

Minecraft 1.16.4 [jar](https://launcher.mojang.com/v1/objects/1952d94a0784e7abda230aae6a1e8fc0522dba99/client.jar)
Minecraft 1.16.4 [obfuscation map](https://launcher.mojang.com/v1/objects/0837de813d1a6b67e23da3c520a84e872c8d2f0e/client.txt) (Right click on it, then click download link)

Full tutorial [here](https://youtu.be/2JVDZzhOFFY) (after downloading the files mentioned above, follow the tutorial from 3:27)

I can't do it because my pc is laggy as hell so it crashes in the middle of decompilation process.

**Comment by AyHa1810** [comment]
Damn why did I even opened this issue on my own repo? Lmao

**Comment by khanhduytran0** [comment]
https://github.com/Hexeption/Optifine-SRC

Optifine SRC including Minecraft source code.
